# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - pre-push
default_stages: [pre-commit]
default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
        args: [--no-allow-dict-kwargs]
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: [--ignore-case, --unique]
        files: project-words.txt
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix, --indent, "4"]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: check_commit
        name: check commit
        stages: [pre-commit]
        entry: devbox
        args: [run, ./check, commit]
        language: system
        require_serial: true
        always_run: true
        fail_fast: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: check_push
        name: check push
        stages: [pre-push]
        entry: devbox
        args: [run, ./check, push]
        language: system
        require_serial: true
        always_run: true
        fail_fast: true
        pass_filenames: false
