# SPDX-FileCopyrightText: 2025-present Krys Lawrence <aquarion.5.krystopher@spamgourmet.org>
# SPDX-License-Identifier: AGPL-3.0-only

command:
  gitignore_excludes: true

formatter:
  type: basic
  line_ending: lf
  retain_line_breaks_single: true
  #max_line_length: 88  # Breaks stuff. :(
  trim_trailing_whitespace: true
  eof_newline: true
