[tool.coverage.run]
source_pkgs = ["aquarion_tts"]
omit = ["src/aquarion_tts/__about__.py"]
branch = true
data_file = ".cache/radish/coverage"

[tool.coverage.report]
show_missing = true
fail_under = 100
#skip_covered = true  # Not sure if I want this.  To try later.
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
