version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025-present Krys Lawrence <aquarion.5.krystopher@spamgourmet.org>"
SPDX-License-Identifier = "AGPL-3.0-only"
path = ".vscode/*"

[[annotations]]
SPDX-FileCopyrightText = "2025-present Krys Lawrence <aquarion.5.krystopher@spamgourmet.org>"
SPDX-License-Identifier = "AGPL-3.0-only"
path = "dev_requirements/**"

[[annotations]]
SPDX-FileCopyrightText = "2025-present Krys Lawrence <aquarion.5.krystopher@spamgourmet.org>"
SPDX-License-Identifier = "AGPL-3.0-only"
path = "devbox.*"

[[annotations]]
SPDX-FileCopyrightText = "2025-present Krys Lawrence <aquarion.5.krystopher@spamgourmet.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = "project-words.txt"

[[annotations]]
SPDX-FileCopyrightText = "2025-present Krys Lawrence <aquarion.5.krystopher@spamgourmet.org>"
SPDX-License-Identifier = "AGPL-3.0-only"
path = "uv.lock"
