# This workflow will install Python dependencies, run tests and lint with a variety of
# Python versions.
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.13"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install devbox # Has it's own cache
              uses: jetify-com/devbox-install-action@v0.12.0

            - name: Cache uv Python
              uses: actions/cache@v4
              with:
                  key: uv-python
                  path: |
                      ~/.local/share/uv/python

            - name: Cache Hatch Pythons
              uses: actions/cache@v4
              with:
                  key: hatch-pythons
                  path: |
                      ~/.local/share/hatch/pythons

            - name: Cache uv dependencies
              uses: actions/cache@v4
              with:
                  key: uv-deps
                  path: |
                      ~/.cache/uv

            - name: Cache pip dependencies
              uses: actions/cache@v4
              with:
                  key: pip-deps
                  path: |
                      ~/.cache/pip

            - name: Initialize environment
              run: devbox run init --ci

            - name: Check types
              run: devbox run check types

            - name: Check lint
              run: devbox run check lint

            - name: Run tests on ${{ matrix.python-version }}
              run: devbox run check test cover -py ${{ matrix.python-version }}

            - name: Run acceptance tests
              run: devbox run check accept cover

            - name: Run security checks
              run: devbox run check sec
